# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 248721671d950aee0efefc0f709ebb975f25350a63f3f562cb4076f3e963e027ca388d7a7f859b3bb35ff9e4b35af6def88c8edad498ff6c2d376cebfd0fcd69

test:
  secret_key_base: bceb52c9982a990d9eba7590b51cbc0625b2f056f16f86d22cf373bbdeb5997b9de7e4af1e5584603c2d4f339fbd24b76194e167c76da00da479b88a56678668

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
